In [1]:
# Problem - 1: Array Creation:
# Complete the following Tasks:
# 1. Initialize an empty array with size 2X2.
# 2. Initialize an all one array with size 4X2.
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

import numpy as np
# 1. Initialize an empty array with size 2x2
a = np.empty((2, 2))
print("Empty 2x2 array:\n", a)

Empty 2x2 array:
 [[0. 0.]
 [0. 0.]]


In [2]:
# 2. Initialize an all-one array with size 4x2
b = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", b)


All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
# 3. Return a new array of given shape and type, filled with a fill value
c = np.full((3, 3), 7)   # Example: 3x3 array filled with 7
print("\nFull array (3x3 filled with 7):\n", c)



Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [4]:
# 4. Return a new array of zeros with same shape and type as a given array
arr = np.array([[1, 2, 3], [4, 5, 6]])
d = np.zeros_like(arr)
print("\nZeros like given array:\n", d)



Zeros like given array:
 [[0 0 0]
 [0 0 0]]


In [5]:
# 5. Return a new array of ones with same shape and type as a given array
e = np.ones_like(arr)
print("\nOnes like given array:\n", e)


Ones like given array:
 [[1 1 1]
 [1 1 1]]


In [6]:
# 6. Convert a list to a numpy array
new_list = [1, 2, 3, 4]
f = np.array(new_list)
print("\nNumpy array from list:\n", f)


Numpy array from list:
 [1 2 3 4]


In [7]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
# 4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
# 6. Create a zero array of size 10 and replace 5th element with 1.
# 7. Reverse an array arr = [1,2,0,0,4,0].
# 8. Create a 2d array with 1 on border and 0 inside.
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.


# 1. Create an array with values ranging from 10 to 49
a = np.arange(10, 50)
print("1. Array 10 to 49:\n", a)



1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 2. Create a 3x3 matrix with values from 0 to 8
b = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix 0 to 8:\n", b)



2. 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 3. Create a 3x3 identity matrix
c = np.eye(3)
print("\n3. Identity Matrix:\n", c)




3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 4. Create a random array of size 30 and find mean
d = np.random.random(30)
print("\n4. Mean of random array:\n", d.mean())


4. Mean of random array:
 0.5002576802895843


In [11]:
# 5. Create a 10x10 random array and find min & max values
e = np.random.random((10, 10))
print("\n5. Min:", e.min(), "  Max:", e.max())


5. Min: 0.013882208781325511   Max: 0.9988852483369935


In [12]:
# 6. Create zero array of size 10 and replace 5th element with 1
f = np.zeros(10)
f[4] = 1     # 5th element (index 4)
print("\n6. Zero array with 5th element = 1:\n", f)



6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# 7. Reverse array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
g = arr[::-1]
print("\n7. Reversed array:\n", g)


7. Reversed array:
 [0 4 0 0 2 1]


In [14]:
# 8. Create a 2D array with 1 on border and 0 inside
h = np.ones((5, 5))
h[1:-1, 1:-1] = 0
print("\n8. 2D array with border of 1 and inside 0:\n", h)


8. 2D array with border of 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# 9. Create an 8x8 checkerboard pattern
i = np.zeros((8, 8), dtype=int)
i[1::2, ::2] = 1
i[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", i)



9. 8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [16]:
# Problem - 3: Array Operations:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
# 2. Subtract the two array.
# 3. Multiply the array with any integers of your choice.
# 4. Find the square of each element of the array.
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy)

1. x + y:
 [[ 6  8]
 [10 13]]


In [17]:
# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. x - y:\n", sub_xy)


2. x - y:
 [[-4 -4]
 [-4 -3]]


In [18]:
# 3. Multiply the array with any integer
mul_x = x * 3
print("\n3. x * 3:\n", mul_x)



3. x * 3:
 [[ 3  6]
 [ 9 15]]


In [19]:
# 4. Square of each element of the array
sq_x = x**2
print("\n4. Square of x:\n", sq_x)


4. Square of x:
 [[ 1  4]
 [ 9 25]]


In [20]:
# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot products:")
print("v · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y:\n", dot_xy)


5. Dot products:
v · w = 219
x · v = [29 77]
x · y:
 [[19 22]
 [50 58]]


In [21]:
# 6. Concatenations
concat_xy_rows = np.concatenate((x, y), axis=0)   # along rows
concat_vw_cols = np.column_stack((v, w))          # along columns

print("\n6. Concatenate x & y along rows:\n", concat_xy_rows)
print("\nConcatenate v & w along columns:\n", concat_vw_cols)


6. Concatenate x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w along columns:
 [[ 9 11]
 [10 12]]


In [22]:
# 7. Concatenate x and v (expect error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x & v:\n", concat_xv)
except ValueError as e:
    print("\n7. Error while concatenating x & v:")
    print(e)
    print("\nExplanation:")
    print("x has shape (2,2) but v has shape (2,).")
    print("Concatenation fails because dimensions do not match.")



7. Error while concatenating x & v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation:
x has shape (2,2) but v has shape (2,).
Concatenation fails because dimensions do not match.


In [23]:
# Problem - 4: Matrix Operations:
# • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ̸= BA.
# 3. Prove (AB)

# T = BTAT
# .

# • Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
# • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
# of Numpy}



# Given Matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
result = A @ A_inv
result = np.round(result).astype(int)

identity = np.eye(2, dtype = int)

print("A * A^-1 =\n", result, "\nI =\n", identity)
if (np.array_equal(result, identity)):
  print("A * A^-1 = I")



A * A^-1 =
 [[1 0]
 [0 1]] 
I =
 [[1 0]
 [0 1]]
A * A^-1 = I


In [24]:
# 2. Prove AB ≠ BA
AB = A @ B
BA = B @ A

print("AB =\n", AB, "\n\nBA =\n", BA)
print("\n")
print("A * B = B * A:", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]] 

BA =
 [[36 44]
 [13 16]]


A * B = B * A: False


In [25]:
# 3. Prove (AB)^T = B^T A^T
LHS = (A @ B).T
RHS = B.T @ A.T

print("LHS =\n", LHS, "\nRHS =\n", RHS)
if (np.array_equal(LHS, RHS)):
  print("(LHS) = (RHS): proved")

LHS =
 [[23 51]
 [13 29]] 
RHS =
 [[23 51]
 [13 29]]
(LHS) = (RHS): proved


In [26]:
# Solve the system of equations:
# 2x − 3y +  z = −1
#  x −  y + 2z = −3
# 3x +  y −  z =  9

A_sys = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

B_sys = np.array([-1, -3, 9])

print("\nSystem Matrix A:\n", A_sys)
print("\nSystem Vector B:\n", B_sys)


System Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

System Vector B:
 [-1 -3  9]


In [27]:
# Solve using inverse method: X = A^-1 * B
A_inv_sys = np.linalg.inv(A_sys)
X = A_inv_sys @ B_sys
print("\nSolution using inverse (x, y, z):\n", X)

# Alternatively using np.linalg.solve
X2 = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:\n", X2)



Solution using inverse (x, y, z):
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


In [28]:
# 4.2 Experiment: How Fast is Numpy?

import time

# python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# numpy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# 1. Element-wise Addition:
# • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
# and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.


# python lists
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise addition of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_add = array1 + array2
end = time.time()

print("Time for element-wise addition of numpy arrays:", end - start, "s")

Time for element-wise addition of python lists: 0.04926776885986328 s
Time for element-wise addition of numpy arrays: 0.0016369819641113281 s


In [29]:
# 2. Element-wise Multiplication
# • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.


# python lists
start = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise multiplication of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_multiply = array1 * array2
end = time.time()

print("Time for element-wise multiplication of numpy arrays:", end - start, "s")

Time for element-wise multiplication of python lists: 0.04879188537597656 s
Time for element-wise multiplication of numpy arrays: 0.0014231204986572266 s


In [30]:
# 3. Dot Product
# • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
# Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.


# python lists
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1000000))
end = time.time()
print("Time for dot-product of python lists:", end - start, end="s\n")

# numpy arrays
start = time.time()
array_dot = np.dot(array1, array2)
end = time.time()

print("Time for dot-product of numpy arrays:", end - start, end="s\n")

Time for dot-product of python lists: 0.05789303779602051s
Time for dot-product of numpy arrays: 0.0006399154663085938s


In [32]:
# 4. Matrix Multiplication
# • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
# and print the time taken for this operation.
# • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


# python matrices
python1 = [[1 for _ in range(1000)] for _ in range(1000)]
python2 = [[1 for _ in range(1000)] for _ in range(1000)]
start = time.time()
python3 = [[sum(python1[i][k] * python2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]
end = time.time()

print("Time for python matrix multiplication:", end - start, "s")

# numpy matrices
np1 = np.ones((1000, 1000))
np2 = np.ones((1000, 1000))

start = time.time()
np3 = np1 @ np2
end = time.time()

print("Time for numpy matrix multiplication:", end - start, "s")

Time for python matrix multiplication: 59.91442823410034 s
Time for numpy matrix multiplication: 0.008764028549194336 s
